version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ReactiveUI.Fody
    versions:
    - "> 10.5.30, < 10.6"
  - dependency-name: FluentFTP
    versions:
    - 33.1.1
    - 33.1.3
    - 33.1.5
    - 33.1.6
    - 33.1.7
  - dependency-name: ReactiveUI.Fody
    versions:
    - 13.1.1
    - 13.2.18
    - 13.2.2
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: CefSharp.Wpf
    versions:
    - 87.1.132
    - 88.2.90
    - 89.0.170
  - dependency-name: CefSharp.OffScreen
    versions:
    - 87.1.132
    - 88.2.90
    - 89.0.170
  - dependency-name: CefSharp.Common.NETCore
    versions:
    - 89.0.170
  - dependency-name: CefSharp.OffScreen.NETCore
    versions:
    - 89.0.170
  - dependency-name: CefSharp.Common
    versions:
    - 87.1.132
    - 88.2.90
    - 89.0.170
  - dependency-name: Fody
    versions:
    - 6.4.0
    - 6.5.0
    - 6.5.1
  - dependency-name: cef.redist.x64
    versions:
    - 89.0.14
    - 89.0.17
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 9.1.4
  - dependency-name: OMODFramework
    versions:
    - 2.2.0
    - 3.0.1
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.30
    - 1.11.31
    - 1.11.32
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Markdig
    versions:
    - 0.23.0
    - 0.24.0
  - dependency-name: MegaApiClient
    versions:
    - 1.9.0
  - dependency-name: ReactiveUI
    versions:
    - 13.1.1
    - 13.2.2
  - dependency-name: ReactiveUI.WPF
    versions:
    - 13.1.1
    - 13.2.2
  - dependency-name: MahApps.Metro
    versions:
    - 2.4.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: PInvoke.User32
    versions:
    - 0.7.104
  - dependency-name: PInvoke.Gdi32
    versions:
    - 0.7.104
  - dependency-name: SharpCompress
    versions:
    - 0.27.1
    - 0.28.0
    - 0.28.1
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 6.0.4
    - 6.0.5
    - 6.0.7
  - dependency-name: Discord.Net.WebSocket
    versions:
    - 2.3.0
