# .NET Desktop
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\\Wabbajack.exe'
    artifact: 'Wabbajack.exe'
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Wabbajack.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'

steps:
- checkout: self
  clean: true
  submodules: true
  
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
