---
Metrics:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: metrics
ListValidation:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: mod_lists
JobQueue:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: job_queue    


