---
Metrics:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: metrics
ListValidation:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: mod_lists
JobQueue:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: job_queue
IndexedFiles:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: indexed_files
NexusModInfos:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: nexus_mod_infos
NexusModFiles:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: nexus_mod_files
NexusFileInfos:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: nexus_file_infos
DownloadStates:
    Host: internal.test.mongodb
    Database: wabbajack
    Collection: download_states
Indexer:
    DownloadDir: c:\tmp\downloads
    TempDir: c:\tmp\tmp
    ArchiveDir: c:\archives
