name: Create Release (Windows)
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: release-builder

    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        run: echo "VERSION=$(python scripts/version_extract.py)" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: buildall.bat
