name: Create Release (Windows)
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: release-builder

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          cd wabbajack\wabbajack
          buildall.bat
