name: Mark Stale

permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v5.0.0
        with:
          stale-issue-message: "Marked as stale due to inactivity. If the issue still exists, please comment as so."
          stale-pr-message: "Marked as stale due to inactivity."
          close-issue-message: "Closed due to inactivity. Please create a new issue if this problem still exists."
          close-pr-message: "Closed due to inactivity."
          days-before-stale: 30
          operations-per-run: 100
          exempt-all-assignees: true
